spring:
  application:
    name: cloud-provider-teach


server:
  port: 9002

eureka:
  client:
    #????????eureka????????????????true
    fetch-registry: true
    #?????eureka???????????????????????true,????????
    register-with-eureka: true
    service-url:
      #defaultZone ????????????????
      #????????service-url,??????map?key-value?????key?defaultZone??????????????????
      #??????????defaultZone?
      defaultZone: http://localhost:9000/eureka
  #????????????
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: 127.0.0.1:9002

feign:
  circuitbreaker: #??????
    enabled: true
  hystrix:
    enabled: true


